---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.50.0

#! Wait rules explicitly define how kapp should wait for resources that kapp does not wait for by default.
#! See: https://carvel.dev/kapp/docs/latest/config/#waitrules.
waitRules:

#! Specify the condition indicating success for Crossplane XRDs.
- conditionMatchers:
    - type: Established
      status: "True"
      success: true
  supportsObservedGeneration: false
  resourceMatchers:
    - apiVersionKindMatcher: { apiVersion: apiextensions.crossplane.io/v1, kind: CompositeResourceDefinition }

#! Change group for Crossplane XRDs.
#! See: https://carvel.dev/kapp/docs/v0.60.x/config/#changegroupbindings.
changeGroupBindings:
  - name: "change-groups.kadras.io/crossplane-xrds"
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: "apiextensions.crossplane.io/v1"
          kind: "CompositeResourceDefinition"

#! Ensure Crossplane Compositions are created after Crossplane XRDs.
#! See: https://carvel.dev/kapp/docs/v0.60.x/config/#changerulebindings.
changeRuleBindings:
  - rules:
      - "upsert after upserting change-groups.kadras.io/crossplane-xrds"
      - "delete before deleting change-groups.kadras.io/crossplane-xrds"
    resourceMatchers:
      - apiVersionKindMatcher:
          apiVersion: "apiextensions.crossplane.io/v1"
          kind: "Composition"
