apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: supply-chains.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: supply-chains.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/supply-chains/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: supply-chains.packages.kadras.io
spec:
  categories:
  - ci/cd
  - golden paths
  - developer experience
  displayName: supply-chains
  longDescription: Supply chains defining golden paths to production for applications and functions, from source code to deployment in a Kubernetes cluster.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Supply chains for applications and functions.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/supply-chains
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: supply-chains
spec:
  packageRef:
    refName: supply-chains.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
